-- ============================================================
-- Seed + Bootstrap: cria tabelas mínimas (se não existirem) e insere raças
-- PostgreSQL 12+
-- ============================================================
CREATE EXTENSION IF NOT EXISTS citext;

-- Tabela especies (mínima)
CREATE TABLE IF NOT EXISTS especies (
  id BIGSERIAL PRIMARY KEY,
  nome_comum CITEXT NOT NULL UNIQUE,
  nome_cientifico TEXT
);

-- Tabela racas (mínima)
CREATE TABLE IF NOT EXISTS racas (
  id BIGSERIAL PRIMARY KEY,
  especie_id BIGINT NOT NULL REFERENCES especies(id) ON DELETE RESTRICT,
  nome CITEXT NOT NULL,
  UNIQUE (especie_id, nome)
);

INSERT INTO especies (nome_comum, nome_cientifico)
VALUES ('cachorro', 'Canis lupus familiaris')
ON CONFLICT (nome_comum) DO NOTHING;

WITH e AS (SELECT id AS especie_id FROM especies WHERE nome_comum = 'cachorro')
INSERT INTO racas (especie_id, nome)
SELECT e.especie_id, x.nome
FROM e
JOIN (
  VALUES
('Affenpinscher'),
  ('Afghan Hound'),
  ('Aidi'),
  ('Airedale Terrier'),
  ('Akita'),
  ('Alano Español'),
  ('Alaskan Malamute'),
  ('American Akita'),
  ('American Bulldog'),
  ('American Cocker Spaniel'),
  ('American English Coonhound'),
  ('American Eskimo Dog'),
  ('American Foxhound'),
  ('American Hairless Terrier'),
  ('American Staffordshire Terrier'),
  ('American Water Spaniel'),
  ('Anatolian Shepherd Dog'),
  ('Appenzeller Sennenhund'),
  ('Ariegeois'),
  ('Austrian Black and Tan Hound'),
  ('Austrian Pinscher'),
  ('Australian Cattle Dog'),
  ('Australian Kelpie'),
  ('Australian Shepherd'),
  ('Australian Silky Terrier'),
  ('Australian Stumpy Tail Cattle Dog'),
  ('Australian Terrier'),
  ('Azawakh'),
  ('Balkan Hound'),
  ('Barbet'),
  ('Basenji'),
  ('Basset Artesien Normand'),
  ('Basset Bleu de Gascogne'),
  ('Basset Fauve de Bretagne'),
  ('Basset Hound'),
  ('Bavarian Mountain Scent Hound'),
  ('Beagle'),
  ('Beagle-Harrier'),
  ('Bearded Collie'),
  ('Beauceron'),
  ('Bedlington Terrier'),
  ('Belgian Laekenois'),
  ('Belgian Malinois'),
  ('Belgian Sheepdog (Groenendael)'),
  ('Belgian Tervuren'),
  ('Bergamasco'),
  ('Berger Picard'),
  ('Bernese Mountain Dog'),
  ('Bichon Frise'),
  ('Biewer Terrier'),
  ('Billy'),
  ('Black and Tan Coonhound'),
  ('Black Norwegian Elkhound'),
  ('Black Russian Terrier'),
  ('Bloodhound'),
  ('Bluetick Coonhound'),
  ('Boerboel'),
  ('Bolognese'),
  ('Border Collie'),
  ('Border Terrier'),
  ('Borzoi'),
  ('Boston Terrier'),
  ('Bouvier des Flandres'),
  ('Boxer'),
  ('Boykin Spaniel'),
  ('Bracco Italiano'),
  ('Braque d''Auvergne'),
  ('Braque du Bourbonnais'),
  ('Braque Francais (Gascogne)'),
  ('Braque Francais (Pyrenees)'),
  ('Braque Saint-Germain'),
  ('Briard'),
  ('Briquet Griffon Vendéen'),
  ('Brittany'),
  ('Broholmer'),
  ('Bruno Jura Hound'),
  ('Brussels Griffon'),
  ('Bull Terrier'),
  ('Bull Terrier (Miniature)'),
  ('Bulldog'),
  ('Bullmastiff'),
  ('Cairn Terrier'),
  ('Canaan Dog'),
  ('Canadian Eskimo Dog'),
  ('Cane Corso'),
  ('Cardigan Welsh Corgi'),
  ('Catahoula Leopard Dog'),
  ('Catalan Sheepdog'),
  ('Caucasian Shepherd Dog'),
  ('Cavalier King Charles Spaniel'),
  ('Central Asian Shepherd Dog'),
  ('Cesky Fousek'),
  ('Cesky Terrier'),
  ('Chesapeake Bay Retriever'),
  ('Chihuahua'),
  ('Chinese Crested'),
  ('Chinese Shar-Pei'),
  ('Chinook'),
  ('Chow Chow'),
  ('Cirneco dell''Etna'),
  ('Clumber Spaniel'),
  ('Cocker Spaniel (English)'),
  ('Collie (Smooth)'),
  ('Coton de Tulear'),
  ('Curly-Coated Retriever'),
  ('Czechoslovakian Wolfdog'),
  ('Dachshund'),
  ('Dalmatian'),
  ('Dandie Dinmont Terrier'),
  ('Danish-Swedish Farmdog'),
  ('Deerhound (Scottish Deerhound)'),
  ('Doberman Pinscher'),
  ('Dogo Argentino'),
  ('Dogo Canario (Presa Canario)'),
  ('Dogue de Bordeaux'),
  ('Drentsche Patrijshond'),
  ('Drever'),
  ('Dutch Shepherd'),
  ('East Siberian Laika'),
  ('English Foxhound'),
  ('English Pointer'),
  ('English Setter'),
  ('English Springer Spaniel'),
  ('English Toy Spaniel'),
  ('Entlebucher Mountain Dog'),
  ('Estonian Hound'),
  ('Estrela Mountain Dog (Cão da Serra da Estrela)'),
  ('Eurasier'),
  ('Field Spaniel'),
  ('Fila Brasileiro'),
  ('Finnish Hound'),
  ('Finnish Lapphund'),
  ('Finnish Spitz'),
  ('Flat-Coated Retriever'),
  ('Fox Terrier (Smooth)'),
  ('French Bulldog'),
  ('French Spaniel'),
  ('Galgo Español'),
  ('Gascon Saintongeois'),
  ('German Hound (Deutscher Bracke)'),
  ('German Longhaired Pointer'),
  ('German Pinscher'),
  ('German Shepherd Dog'),
  ('German Shorthaired Pointer'),
  ('German Spaniel (Wachtelhund)'),
  ('German Spitz'),
  ('German Wirehaired Pointer'),
  ('Giant Schnauzer'),
  ('Glen of Imaal Terrier'),
  ('Golden Retriever'),
  ('Gordon Setter'),
  ('Grand Anglo-Français Blanc et Noir'),
  ('Grand Anglo-Français Blanc et Orange'),
  ('Grand Anglo-Français Tricolore'),
  ('Grand Basset Griffon Vendéen'),
  ('Grand Bleu de Gascogne'),
  ('Great Dane'),
  ('Great Pyrenees'),
  ('Greater Swiss Mountain Dog'),
  ('Greek Harehound'),
  ('Greenland Dog'),
  ('Greyhound'),
  ('Griffon Nivernais'),
  ('Halden Hound'),
  ('Hamiltonstövare'),
  ('Hanoverian Scenthound'),
  ('Harrier'),
  ('Havanese'),
  ('Hokkaido'),
  ('Hovawart'),
  ('Ibizan Hound'),
  ('Icelandic Sheepdog'),
  ('Irish Red and White Setter'),
  ('Irish Setter'),
  ('Irish Terrier'),
  ('Irish Water Spaniel'),
  ('Irish Wolfhound'),
  ('Istrian Coarse-haired Hound'),
  ('Istrian Shorthaired Hound'),
  ('Italian Greyhound'),
  ('Italian Hound (Segugio Italiano)'),
  ('Jack Russell Terrier'),
  ('Japanese Akitainu'),
  ('Japanese Chin'),
  ('Japanese Spitz'),
  ('Japanese Terrier'),
  ('Jindo'),
  ('Jagdterrier (German Hunt Terrier)'),
  ('Kai Ken'),
  ('Kangal Shepherd Dog'),
  ('Karelian Bear Dog'),
  ('Keeshond'),
  ('Kerry Blue Terrier'),
  ('Kintamani-Bali Dog'),
  ('Kishu Ken'),
  ('Komondor'),
  ('Kromfohrländer'),
  ('Kuvasz'),
  ('Nederlandse Kooikerhondje'),
  ('Labrador Retriever'),
  ('Lagotto Romagnolo'),
  ('Lakeland Terrier'),
  ('Lancashire Heeler'),
  ('Landseer (ECT)'),
  ('Lapponian Herder'),
  ('Large Munsterlander'),
  ('Leonberger'),
  ('Lhasa Apso'),
  ('Löwchen'),
  ('Maltese'),
  ('Manchester Terrier'),
  ('Maremma Sheepdog'),
  ('Mastiff'),
  ('Miniature American Shepherd'),
  ('Miniature Bull Terrier'),
  ('Miniature Pinscher'),
  ('Miniature Schnauzer'),
  ('Mudi'),
  ('Magyar Agár'),
  ('Neapolitan Mastiff'),
  ('Newfoundland'),
  ('Norfolk Terrier'),
  ('Norwegian Buhund'),
  ('Norwegian Elkhound (Grey)'),
  ('Norwegian Lundehund'),
  ('Norwich Terrier'),
  ('Nova Scotia Duck Tolling Retriever'),
  ('Norrbottenspets'),
  ('Old English Sheepdog'),
  ('Otterhound'),
  ('Papillon'),
  ('Parson Russell Terrier'),
  ('Pekingese'),
  ('Pembroke Welsh Corgi'),
  ('Perdigueiro Português (Portuguese Pointer)'),
  ('Perro de Agua Español (Spanish Water Dog)'),
  ('Peruvian Hairless Dog'),
  ('Petit Basset Griffon Vendéen'),
  ('Petit Bleu de Gascogne'),
  ('Pharaoh Hound'),
  ('Picardy Spaniel'),
  ('Plott Hound'),
  ('Podenco Canario'),
  ('Polish Greyhound (Chart Polski)'),
  ('Polish Hound (Ogar Polski)'),
  ('Polish Lowland Sheepdog'),
  ('Polish Tatra Sheepdog'),
  ('Pomeranian'),
  ('Pont-Audemer Spaniel'),
  ('Poodle'),
  ('Porcelaine'),
  ('Portuguese Podengo'),
  ('Portuguese Podengo Pequeno'),
  ('Portuguese Sheepdog (Cão da Serra de Aires)'),
  ('Portuguese Water Dog'),
  ('Pražský Krysařík (Prazsky Krysarik)'),
  ('Pudelpointer'),
  ('Pug'),
  ('Puli'),
  ('Pumi'),
  ('Pyrenean Mastiff'),
  ('Pyrenean Shepherd'),
  ('Rafeiro do Alentejo'),
  ('Rat Terrier'),
  ('Redbone Coonhound'),
  ('Rhodesian Ridgeback'),
  ('Romanian Carpathian Shepherd Dog'),
  ('Romanian Mioritic Shepherd Dog'),
  ('Rottweiler'),
  ('Rough Collie'),
  ('Saarloos Wolfdog'),
  ('Saint Bernard'),
  ('Saluki'),
  ('Samoyed'),
  ('Šarplaninac (Sarplaninac)'),
  ('Schapendoes'),
  ('Schipperke'),
  ('Standard Schnauzer'),
  ('Scottish Terrier'),
  ('Sealyham Terrier'),
  ('Segugio Maremmano'),
  ('Shetland Sheepdog'),
  ('Shiba Inu'),
  ('Shih Tzu'),
  ('Shikoku'),
  ('Siberian Husky'),
  ('Silky Terrier'),
  ('Skye Terrier'),
  ('Sloughi'),
  ('Slovakian Wirehaired Pointer'),
  ('Slovenský čuvač (Slovak Cuvac)'),
  ('Small Munsterlander'),
  ('Soft Coated Wheaten Terrier'),
  ('Spanish Mastiff (Mastín Español)'),
  ('Spinone Italiano'),
  ('Stabyhoun'),
  ('Staffordshire Bull Terrier'),
  ('Sussex Spaniel'),
  ('Swedish Elkhound (Jämthund)'),
  ('Swedish Lapphund'),
  ('Swedish Vallhund'),
  ('Taigan'),
  ('Thai Bangkaew Dog'),
  ('Thai Ridgeback'),
  ('Tibetan Mastiff'),
  ('Tibetan Spaniel'),
  ('Tibetan Terrier'),
  ('Tornjak'),
  ('Tosa'),
  ('Transylvanian Hound'),
  ('Treeing Walker Coonhound'),
  ('Vizsla'),
  ('Volpino Italiano'),
  ('Weimaraner'),
  ('Welsh Springer Spaniel'),
  ('Welsh Terrier'),
  ('West Highland White Terrier'),
  ('Wetterhoun'),
  ('Whippet'),
  ('Wire Fox Terrier'),
  ('Wirehaired Pointing Griffon'),
  ('Wirehaired Vizsla'),
  ('Xoloitzcuintli'),
  ('Yakutian Laika'),
  ('Yorkshire Terrier')
) AS x(nome) ON TRUE
ON CONFLICT (especie_id, nome) DO NOTHING;
